owner: agudovich
repo: status-page

sites:
  - name: Personal Bio (gudovich.me)
    url: https://gudovich.me
  - name: Print Cut E-commerce
    url: https://printcut.pro
  - name: TAGIO 
    url: https://tagio.id
  - name: Telegram Bot API (Health Check)
    url: https://api.telegram.org/bot$8417060238:AAFLCY0_oGu0OeViwMnTeFFowLYZoSX2kac/getMe
    method: GET

status-website:
  cname: status.gudovich.me # Если захочешь привязать свой домен
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Service Status"
  introMessage: "Мониторинг сервисов"

notifications:
  - type: telegram
navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
